# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: (ASKotec) Training - Module Resource Template
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  ASKotec test site. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Training.Module.Resource.Template" # the subpath of your site, e.g. /blog
url: "https://opencultureagency.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repo_browse_url: "https://github.com/opencultureagency/Training.Module.Resource.Template/"
repo_raw_url: "https://raw.githubusercontent.com/opencultureagency/Training.Module.Resource.Template/"
git_ref: "main"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
plugins:
    - jekyll-rdf
#  - jekyll-feed

jekyll_rdf:
  baseiri: "http://myontology.com/"
  path: "_data/resource.ttl"
  default_template: "default.html"
  #restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), 'http://myontology.com/Module')  }"
  #restriction: "SELECT ?subjectUri WHERE { ?subjectUri ?p ?o . FILTER regex(str(?subjectUri), 'http://myontology.com/Module')  }"
  class_template_mappings:
    "http://myontology.com/Resource": "resource.html"
  #instance_template_mappings:
    #"http://example.org/simpsons/Abraham": "abraham.html"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
