  version: '1.0'

training-module-content:
    authors:
        - name: Name of the author
          github-profile: 
          contact: 
    release: 1.0
    categories:
    duration: HH:MM
    difficulty:
    cost:
    language: en
    connected-platforms:
        - blog:
        - telegram:
        - wikifab: 
        - other:
    new-issue: # generate url to new issue
    license:
        name: # generate name from repo
        file: # generate file link from repo. If there is no file in root then link to repo.
    manual: Manual.md # if the manual file has the manual.md filename it could be generated
